sitereservation_addeventform:
    pattern:  /addevent
    defaults: { _controller: sitereservationBundle:Default:addevent }
sitereservation_addnewuserform:
    pattern:  /adduser
    defaults: { _controller: sitereservationBundle:Default:addnewuser }
sitereservation_homepage:
    pattern:  /home
    defaults: { _controller: sitereservationBundle:Site:index }

sitereservation_companysignup:
    pattern:  /companysignup
    defaults: { _controller: sitereservationBundle:Site:sucompany }

sitereservation_submitcompanysu:
    pattern:  /submitcompanysu
    defaults: { _controller: sitereservationBundle:Site:companySubmit }

sitereservation_GuestOffers:
    pattern:  /guestoffers
    defaults: { _controller: sitereservationBundle:Site:getAllOffers }

sitereservation_CompanyMenu:
    pattern:  /companyMenu/{company}
    defaults: { _controller: sitereservationBundle:Site:companyMenu }

sitereservation_companyprofile:
    pattern:  /company/{name}
    defaults: { _controller: sitereservationBundle:Site:companyProfile }

sitereservation_AllCompanies:
    pattern:  /companies
    defaults: { _controller: sitereservationBundle:Site:allCompanies }
sitereservation_Gcusthome:
    pattern:  /custhome
    defaults: { _controller: sitereservationBundle:Site:custhome }
sitereservation_userprofile:
    pattern:  /userprofile
    defaults: { _controller: sitereservationBundle:Site:UserProfile }    
sitereservation_userserviceprovider:
    pattern:  /userprofile
    defaults: { _controller: sitereservationBundle:Site:UserserviceProvider }    