sitereservation_homepage:
    pattern:  /home
    defaults: { _controller: sitereservationBundle:Site:index }

sitereservation_companysignup:
    pattern:  /companysignup
    defaults: { _controller: sitereservationBundle:Site:sucompany }

sitereservation_submitcompanysu:
    pattern:  /submitcompanysu
    defaults: { _controller: sitereservationBundle:Site:companySubmit }

sitereservation_GuestOffers:
    pattern:  /guestoffers
    defaults: { _controller: sitereservationBundle:Site:getAllOffers }

sitereservation_CompanyMenu:
    pattern:  /companyMenu/{company}/{id}/{page}
    defaults: { _controller: sitereservationBundle:Site:companyMenu , id : 1 , page: 1}

sitereservation_companyprofile:
    pattern:  /company/{id}
    defaults: { _controller: sitereservationBundle:Site:companyProfile }

sitereservation_AllCompanies:
    pattern:  /companies/{id}/{page}
    defaults: { _controller: sitereservationBundle:Site:allCompanies , id : 1 , page: 1}

sitereservation_address:
    pattern:  /companiesAdd/{id}
    defaults: { _controller: sitereservationBundle:Site:getAddressCompany }

sitereservation_about:
    pattern:  /about
    defaults: { _controller: sitereservationBundle:Site:about }
    
sitereservation_contactus:
    pattern:  /contactus/{id}
    defaults: { _controller: sitereservationBundle:Default:contactus }
    
sitereservation_eventcat:
    pattern:  /eventscatuser/{cat}/{id}/{page}
    defaults: { _controller: sitereservationBundle:Site:eventcatuser , id : 1 , page: 1 }
    
sitereservation_EventProfileinfo:
    pattern: /eventprof/{id} 
    defaults: { _controller: sitereservationBundle:Site:profileoffer }
    
sitereservation_userAllOffers:
    pattern:  /allOffersuser/{id}/{page}
    defaults: { _controller: sitereservationBundle:Site:alloffersuser , id : 1 , page: 1 }

sitereservation_Gcusthome:
    pattern:  /custhome
    defaults: { _controller: sitereservationBundle:Site:custhome }
    
sitereservation_extrauserinfo:
    pattern:  /extrauser/{id}
    defaults: { _controller: sitereservationBundle:Default:extrauser }
    
sitereservation_hobbiesuserinfo:
    pattern:  /hobbiesuser/{id}
    defaults: { _controller: sitereservationBundle:Default:hobbiesuser }
    
sitereservation_addnewuserform:
    pattern:  /adduser
    defaults: { _controller: sitereservationBundle:Default:addnewuser }
    
sitereservation_addeventform:
    pattern:  /addevent
    defaults: { _controller: sitereservationBundle:Default:addevent }
    
sitereservation_signOut:
    pattern: /signOut
    defaults: { _controller: sitereservationBundle:Site:signOut }
    
sitereservation_userserviceprovider:
    pattern:  /userservice
    defaults: { _controller: sitereservationBundle:Site:UserserviceProvider }
    
sitereservation_userprofile:
    pattern:  /userprofile
    defaults: { _controller: sitereservationBundle:Site:UserProfile }
    
sitereservation_signIn:
    pattern: /signIn
    defaults: {_controller: sitereservationBundle:Site:signIn }
    
sitereservation_index:
    pattern:  /
    defaults: { _controller: sitereservationBundle:Site:index }
    
sitereservation_firstSignIn:
    pattern: /fristSignIn/{id}
    defaults: { _controller: sitereservationBundle:Site:firstSignIn }
    
sitereservation_addNewCompany:
    pattern: /home/addNewCompany
    defaults: { _controller: sitereservationBundle:Default:addNewCompany }

sitereservation_addNewCompanyInfo:
    pattern: /home/addNewCompanyInfo/{id}
    defaults: { _controller: sitereservationBundle:Default:addNewCompanyInfo }
    
sitereservation_addNewCompanyAdress:
    pattern: /home/addNewCompanyAddress/{id}
    defaults: { _controller: sitereservationBundle:Default:addNewCompanyAddress }
    
sitereservation_registeroffer:
    pattern: /registeroffer/{id}/{eventid}
    defaults: { _controller: sitereservationBundle:Site:registeroffer }
    
sitereservation_deleteoffer:
    pattern: /deleteoffer/{id}/{eventid}
    defaults: { _controller: sitereservationBundle:Site:deleteoffer }
    
sitereservation_publishoffer:
    pattern: /publishoffer/{id}/{eventid}/{state}
    defaults: { _controller: sitereservationBundle:Site:publishoffer }
    
sitereservationBundle_getcompanycat:
    pattern: /compcat
    defaults: { _controller: sitereservationBundle:Site:getcompcat }
    
sitereservationBundle_msgsent:
    pattern: /msgsent/{id}
    defaults: { _controller: sitereservationBundle:Site:sendmessageusercomp }
    
sitereservation_search:
    pattern: /search
    defaults: { _controller: sitereservationBundle:Site:search }

sitereservation_restInfoCompany:
    pattern: /restInfoCompany/{id}
    defaults: { _controller: sitereservationBundle:Site:restInfoComp }
    
sitereservation_calender:
    pattern:  /calendar
    defaults: { _controller: sitereservationBundle:Site:calendar }

sitereservation_cities:
    pattern:  /cities
    defaults: { _controller: sitereservationBundle:Site:getcities }

sitereservation_calendardata:
    pattern:  /calendardata
    defaults: { _controller: sitereservationBundle:Site:putcalendardata }
    
sitereservation_homeuser:
    pattern:  /userhome
    defaults: { _controller: sitereservationBundle:Site:homeuser }
    
sitereservation_AllCompaniesuser:
    pattern:  /companiesuser
    defaults: { _controller: sitereservationBundle:Site:allCompaniesuser }
    
sitereservationBundle_showmessages:
    pattern: /showmessages
    defaults: { _controller: sitereservationBundle:Site:showmessages }
    
sitereservation_signInPageForSmallDevice:
    pattern: /signInPage
    defaults: { _controller: sitereservationBundle:Site:signInPageForSmallDevice }
    
sitereservation_AdminReports:
    pattern: /admin/reports
    defaults: { _controller: sitereservationBundle:Site:getAllReports }

sitereservation_AdminProfile:
    pattern: /admin/adminProfile
    defaults: { _controller: sitereservationBundle:Site:adminProfile }
     
sitereservation_AdminAddData:
    pattern: /admin/adminAddData
    defaults: { _controller: sitereservationBundle:Site:adminAddData }

sitereservation_activeNewCompany:
    pattern: /admin/adminAddData/activeNewCompany
    defaults: { _controller: sitereservationBundle:Site:activeNewCompanyrequest }
    
sitereservation_addPaymentForCompany:
    pattern: /admin/adminAddData/addPaymentForCompany
    defaults: { _controller: sitereservationBundle:Site:addPaymentForCompany }

sitereservation_showUnPaymentCompany:
    pattern: /admin/reports/showUnPaymentCompany
    defaults: { _controller: sitereservationBundle:Site:showUnPaymentCompany }

sitereservation_showActiveUserReport:
    pattern: /admin/reports/showActiveUser
    defaults: { _controller: sitereservationBundle:Site:showActiveUser }

sitereservation_showUnActiveUserReport:
    pattern: /admin/reports/showUnActiveUser
    defaults: { _controller: sitereservationBundle:Site:showUnActiveUser }

