sitereservation_index:
    pattern:  /
    defaults: { _controller: sitereservationBundle:Site:index }

sitereservation_homepage:
    pattern:  /home
    defaults: { _controller: sitereservationBundle:Site:index }

sitereservation_companysignup:
    pattern:  /companysignup
    defaults: { _controller: sitereservationBundle:Site:sucompany }

sitereservation_submitcompanysu:
    pattern:  /submitcompanysu
    defaults: { _controller: sitereservationBundle:Site:companySubmit }

sitereservation_GuestOffers:
    pattern:  /guestoffers
    defaults: { _controller: sitereservationBundle:Site:getAllOffers }

sitereservation_signIn:
    pattern: /signIn
    defaults: {_controller: sitereservationBundle:Site:signIn }
    
sitereservation_CompanyMenu:
    pattern:  /companyMenu/{company}
    defaults: { _controller: sitereservationBundle:Site:companyMenu }
    
sitereservation_companyprofile:
    pattern:  /company/{id}
    defaults: { _controller: sitereservationBundle:Site:companyProfile }
    
sitereservation_AllCompanies:
    pattern:  /companies
    defaults: { _controller: sitereservationBundle:Site:allCompanies }

sitereservation_address:
    pattern:  /companiesAdd/{id}
    defaults: { _controller: sitereservationBundle:Site:getAddressCompany }
    
sitereservation_userprofile:
    pattern:  /userprofile
    defaults: { _controller: sitereservationBundle:Site:UserProfile } 
    
sitereservation_userserviceprovider:
    pattern:  /userprofile
    defaults: { _controller: sitereservationBundle:Site:UserserviceProvider }

sitereservation_signOut:
    pattern: /signOut
    defaults: { _controller: sitereservationBundle:Site:signOut }
