<?php

namespace site\reservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * addressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class addressRepository extends EntityRepository
{
	public function getCompanyAddress($id)
	{
		$query = $this->getEntityManager()->createQuery('
				SELECT A
				FROM sitereservationBundle:Address A
				JOIN A.comp c
				where c.id like :id
			');
		$query->setParameter('id',$id);
		return $query->getSingleResult();
	}
}
