<?php

namespace site\reservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * calenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class calendarRepository extends EntityRepository
{
}
