<?php

namespace site\reservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository {

    public function getProfileInfo($custid) {

        $query = $this->getEntityManager()->createQuery('
            
                         SELECT C 
                         from sitereservationBundle:Customer C
                         where C.id= :id
                    ');
        $query->setParameter('id',$custid);
		return $query->getResult();
       
       
    }
    
    
    public function getCustomerInfo($email,$pass){
        
        $query = $this->getEntityManager()->createQuery('
            
                select c
                from sitereservationBundle:customer c
                where c.email = :email and c.password = :pass

        ');
        
        $query->setParameter('email', $email);
        $query->setParameter('pass',$pass);
        
        return $query->getResult();
        
    }

}
