<?php

namespace site\reservationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use site\reservationBundle\Entity\Customer;

/**
 * InfocompRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfocompRepository extends EntityRepository
{
	public function getCompanies($company,$id,$page,$maxResult)
	{
		 if($page<1){
        return array();
   			 }
    	--$page;
		$query = $this->getEntityManager()->createQuery('
				SELECT I
				FROM sitereservationBundle:Infocomp I
				JOIN I.custid c
				where I.category like :cat
			');
		$query->setParameter('cat',$company);
		if($maxResult){
            $query->setFirstResult($page * $maxResult);
            $query->setMaxResults($maxResult);
        }
		return $query->getResult();
	}
	public function getAllCompanies($id,$page,$maxResult)
	{
		 if($page<1){
        return array();
   			 }
    	--$page;
		$query = $this->getEntityManager()->createQuery('
				SELECT I
				FROM sitereservationBundle:Infocomp I
				JOIN I.custid c
			');
		if($maxResult){
            $query->setFirstResult($page * $maxResult);
            $query->setMaxResults($maxResult);
        }
		return $query->getResult();
	}
    public function getthisCompany($id)
	{
		$query = $this->getEntityManager()->createQuery('
				SELECT I
				FROM sitereservationBundle:Infocomp I
				JOIN I.custid c
				where I.custid = :id
			');
		$query->setParameter('id',$id);
		return $query->getSingleResult();
	}
	public function getCount()
    {
     
       $query = $this->getEntityManager()->createQuery('
            SELECT count(I) as counts
            FROM sitereservationBundle:Infocomp I
            ');
        return $query->getResult();
    }
    public function getTypeCount($company)
    {
       $query = $this->getEntityManager()->createQuery('
            SELECT count(I) as counts
            FROM sitereservationBundle:Infocomp I
            where I.category = :cat
            ');
       $query->setParameter("cat",$company);
        return $query->getResult();
    }

        
}
