<?php

namespace site\reservationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use site\reservationBundle\Entity\Customer;

/**
 * InfocompRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfocompRepository extends EntityRepository
{
	public function getCompanies($company)
	{
		$query = $this->getEntityManager()->createQuery('
				SELECT I
				FROM sitereservationBundle:Infocomp I
				JOIN I.custid c
				where I.category like :cat
			');
		$query->setParameter('cat',$company);
		return $query->getResult();
	}
	/*public function getAllCompanies()
	{
		$query = $this->getEntityManager()->createQuery('
				SELECT I
				FROM sitereservationBundle:Infocomp I
				JOIN I.customer c
			');
		return $query->getResult();
	}*/
        
        
}
