<?php

namespace site\reservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * messagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messagesRepository extends EntityRepository
{
    public function getmessages($rid){
        $query = $this->getEntityManager()->createQuery('
				SELECT M
				FROM sitereservationBundle:Messages M
				where M.msgto = :rid
                                and M.checked like :chk
			');
		$query->setParameter('rid',$rid);
                $query->setParameter('chk','no');
		return $query->getResult();
    }
}
