<?php

namespace site\reservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserinfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserinfoRepository extends EntityRepository
{
    
     public function getProfileInfoUser($id) {
    

        $query = $this->getEntityManager()->createQuery('
            
                         SELECT U 
                         From sitereservationBundle:Userinfo U
                         where U.custid = :id
                    ');
        
        $query->setParameter('id', $id);
        return  $query->getResult();
    }
    
}
